version: '3.7'

# Source:
# https://www.twilio.com/blog/get-started-docker-symfony
# https://github.com/symfony/panther
# https://x-team.com/blog/set-up-rabbitmq-with-docker-compose/
# https://dev.to/fabiothiroki/introduction-to-rabbitmq-and-symfony-2an4
services:

  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/instagram_parser
    depends_on:
      - mysql
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.5-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - php
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/instagram_parser
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge